Update action_utest.yml

diff --git a/.github/workflows/action_utest.yml b/.github/workflows/action_utest.yml
--- a/.github/workflows/action_utest.yml
+++ b/.github/workflows/action_utest.yml
@@ -158,13 +158,12 @@ jobs:
 
             if [[ "$line" == *"[==========] [ utest    ] end"* ]]; then
               echo "Utest run completed. Exiting log monitoring..."
+              if $FAILURE_DETECTED; then
+                echo "Error: Failures detected in logs. Below are the failure details:"
+                echo "$ERROR_LOGS"
+                exit 1
+              fi
               break
             fi
-          break
         done
-
-        if $FAILURE_DETECTED; then
-          echo "Error: Failures detected in logs. Below are the failure details:"
-          echo "$ERROR_LOGS"
-          exit 1
-        fi
+        
