Update action_utest.yml

diff --git a/.github/workflows/action_utest.yml b/.github/workflows/action_utest.yml
--- a/.github/workflows/action_utest.yml
+++ b/.github/workflows/action_utest.yml
@@ -148,20 +148,19 @@ jobs:
         FAILURE_DETECTED=false
         ERROR_LOGS=""
         
-        while true; do
-          tail -n 0 -f qemu_output.log | while read line; do
-            if [[ "$line" == *"[  PASSED  ] [ result   ]"* ]]; then
-              ERROR_LOGS="$ERROR_LOGS$line"$'\n'
-              echo "$line"
-              FAILURE_DETECTED=true
-            fi
+        tail -n 0 -f qemu_output.log | while read line; do
+          if [[ "$line" == *"[  PASSED  ] [ result   ]"* ]]; then
+            ERROR_LOGS="$ERROR_LOGS$line"$'\n'
+            echo "$line"
+            FAILURE_DETECTED=true
+          fi
 
-            if [[ "$line" == *"[==========] [ utest    ] end"* ]]; then
-              echo "Utest run completed. Exiting log monitoring..."
-              if $FAILURE_DETECTED; then
-                echo "Error: Failures detected in logs. Below are the failure details:"
-                echo "$ERROR_LOGS"
-                exit 1
-              fi
-              break
+          if [[ "$line" == *"[==========] [ utest    ] end"* ]]; then
+            echo "Utest run completed. Exiting log monitoring..."
+            if $FAILURE_DETECTED; then
+              echo "Error: Failures detected in logs. Below are the failure details:"
+              echo "$ERROR_LOGS"
+              exit 1
             fi
+            break
+          fi
