Update action_utest.yml

diff --git a/.github/workflows/action_utest.yml b/.github/workflows/action_utest.yml
--- a/.github/workflows/action_utest.yml
+++ b/.github/workflows/action_utest.yml
@@ -162,9 +162,9 @@ jobs:
             fi
           done
 
-          if $FAILURE_DETECTED; then
-            echo "Error: Failures detected in logs. Below are the failure details:"
-            echo "$ERROR_LOGS"
-            exit 1
-          fi
+        if $FAILURE_DETECTED; then
+          echo "Error: Failures detected in logs. Below are the failure details:"
+          echo "$ERROR_LOGS"
+          exit 1
+        fi
         done
